# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WKY Developers
tagline:          'Western Kentucky Developers User Group'
description:      'Developers and engineers from Western Kentucky meeting to share and discuss ideas around software development'
url:              http://wkydev.com

author:
  name:           'WKYDev'
  url:            https://twitter.com/wkydev

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/wkydev/wkydev.github.io
